#!/usr/bin/php
<?php

use Phelper\App;
use App\Command\HelpCommand;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$app = new App();
$helpCommand = new HelpCommand;

$app->registerCommand($helpCommand, function (array $argv) use ($app, $helpCommand) {
    $app->getPrinter()->display($helpCommand->getDescription());
});

$app->runCommand($argv);