#!/usr/bin/php
<?php

use Phelper\App;
use App\Command\HelloController;
use Phelper\Command;
use Phelper\CommandRegistry;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$app = new App();
$defaultCommand = new Command('help');
$commands = new CommandRegistry();

$app->registerController(new Command('hello'), new HelloController($app));

$app->registerCommand($defaultCommand, function (array $argv) use ($app) {
    $app->getPrinter()->display("usage: Phelper hello [ your-name ]");
});

$app->runCommand($argv);